# Используем официальный образ PostgreSQL
FROM postgres:latest

# Устанавливаем переменные окружения для пользователя, пароля и базы данных
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase

# Открываем порт 5432 для подключения
EXPOSE 5432